image: Ubuntu  # образ для сборки

stack: jdk 1111  # версия JDK
                             
branches:
  только:
    - main  # ветка git

build: off  # свой скрипт сборки

install:
запускаем SUT (& означает, будем использовать 
  - java -jar ./artifacts/app-card-delivery.jar &
  - chmod +x gradlew

build_script:
 ./gradlew test -Dselenide(GRADLew_)_o
